# Usa una imagen base de Python
FROM python:3.8

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos requeridos a /app
COPY . /app

# Instala las dependencias
RUN pip install pika mysql-connector-python

# Ejecuta el script consumidor
CMD ["python", "consumidor.py"]
